# To use:
# Run "docker-compose build" to rebuild the app container.
# Run "docker-compose run php8" to run the test script.
# Run "docker-compose down -v" to fully wipe everything and start over.

version: "3"
services:
    php8:
        build: .
        volumes:
            - .:/usr/src/myapp
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        depends_on:
            -   db
        environment:
            PHP_IDE_CONFIG: "serverName=Rekodi"
            XDEBUG_MODE: "develop,debug"
            XDEBUG_CONFIG: "client_host=172.17.0.1 idekey=docker-xdebug discover_client_host=1 start_with_request=1"
#        extra_hosts:
#            - "host.docker.internal:host-gateway"
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: rekodi
        ports:
            - 3306:3306
